-- SPDX-License-Identifier: GPL-3.0-only

---@meta _

-------------------------------------------------------
-- Engine tag types
-------------------------------------------------------

---@alias TagGroup
---| "actor"
---| "actor_variant"
---| "antenna"
---| "model_animations"
---| "biped"
---| "bitmap"
---| "spheroid"
---| "continuous_damage_effect"
---| "model_collision_geometry"
---| "color_table"
---| "contrail"
---| "device_control"
---| "decal"
---| "ui_widget_definition"
---| "input_device_defaults"
---| "device"
---| "detail_object_collection"
---| "effect"
---| "equipment"
---| "flag"
---| "fog"
---| "font"
---| "material_effects"
---| "garbage"
---| "glow"
---| "grenade_hud_interface"
---| "hud_message_text"
---| "hud_number"
---| "hud_globals"
---| "item"
---| "item_collection"
---| "damage_effect"
---| "lens_flare"
---| "lightning"
---| "device_light_fixture"
---| "light"
---| "sound_looping"
---| "device_machine"
---| "globals"
---| "meter"
---| "light_volume"
---| "gbxmodel"
---| "model"
---| "multiplayer_scenario_description"
---| "null"
---| "preferences_network_game"
---| "object"
---| "particle"
---| "particle_system"
---| "physics"
---| "placeholder"
---| "point_physics"
---| "projectile"
---| "weather_particle_system"
---| "scenario_structure_bsp"
---| "scenery"
---| "shader_transparent_chicago_extended"
---| "shader_transparent_chicago"
---| "scenario"
---| "shader_environment"
---| "shader_transparent_glass"
---| "shader"
---| "sky"
---| "shader_transparent_meter"
---| "sound"
---| "sound_environment"
---| "shader_model"
---| "shader_transparent_generic"
---| "ui_widget_collection"
---| "shader_transparent_plasma"
---| "sound_scenery"
---| "string_list"
---| "shader_transparent_water"
---| "tag_collection"
---| "camera_track"
---| "dialogue"
---| "unit_hud_interface"
---| "unit"
---| "unicode_string_list"
---| "virtual_keyboard"
---| "vehicle"
---| "weapon"
---| "wind"
---| "weapon_hud_interface"

---@alias TagData
---| TagDataActor
---| TagDataActorVariant
---| TagDataAntenna
---| TagDataModelAnimations
---| TagDataBiped
---| TagDataBitmap
---| TagDataContinuousDamageEffect
---| TagDataModelCollisionGeometry
---| TagDataColorTable
---| TagDataContrail
---| TagDataDeviceControl
---| TagDataDecal
---| TagDataUiWidgetDefinition
---| TagDataInputDeviceDefaults
---| TagDataDevice
---| TagDataDetailObjectCollection
---| TagDataEffect
---| TagDataEquipment
---| TagDataFlag
---| TagDataFog
---| TagDataFont
---| TagDataLightning
---| TagDataMaterialEffects
---| TagDataGarbage
---| TagDataGlow
---| TagDataGrenadeHudInterface
---| TagDataHudMessageText
---| TagDataHudNumber
---| TagDataHudGlobals
---| TagDataItem
---| TagDataItemCollection
---| TagDataDamageEffect
---| TagDataLensFlare
---| TagDataDeviceLightFixture
---| TagDataLight
---| TagDataSoundLooping
---| TagDataDeviceMachine
---| TagDataGlobals
---| TagDataMeter
---| TagDataLightVolume
---| TagDataGbxmodel
---| TagDataModel
---| TagDataMultiplayerScenarioDescription
---| TagDataPreferencesNetworkGame
---| TagDataObject
---| TagDataParticle
---| TagDataParticleSystem
---| TagDataPhysics
---| TagDataPlaceholder
---| TagDataPointPhysics
---| TagDataProjectile
---| TagDataWeatherParticleSystem
---| TagDataScenarioStructureBsp
---| TagDataScenery
---| TagDataShaderTransparentChicagoExtended
---| TagDataShaderTransparentChicago
---| TagDataScenario
---| TagDataShaderEnvironment
---| TagDataShaderTransparentGlass
---| TagDataShader
---| TagDataSky
---| TagDataShaderTransparentMeter
---| TagDataSound
---| TagDataSoundEnvironment
---| TagDataShaderModel
---| TagDataShaderTransparentGeneric
---| TagDataTagDataUiWidgetCollect
---| TagDataUiWidgetCollection
---| TagDataShaderTransparentPlasma
---| TagDataSoundScenery
---| TagDataStringList
---| TagDataShaderTransparentWater
---| TagDataTagCollection
---| TagDataCameraTrack
---| TagDataUnitHudInterface
---| TagDataUnit
---| TagDataUnicodeStringList
---| TagDataVirtualKeyboard
---| TagDataVehicle
---| TagDataWeapon
---| TagDataWind
---| TagDataWeaponHudInterface

---@class TagHandle
---@field value integer
---@field index integer
---@field id integer
---@field isNull fun(): boolean

---@class TagEntry
---@field path string
---@field handle TagHandle
---@field primaryGroup TagGroup
---@field secondaryGroup TagGroup
---@field tertiaryGroup TagGroup
local TagEntry = {}

-- Returns the data of the tag.
---@return TagData
function TagEntry:getData() end

---@class TagReference
---@field tagHandle TagHandle
---@field tagGroup TagGroup

---@class TagRawData
---@field pointer integer
---@field size integer

---@class ScenarioScriptNodeValue
