// SPDX-License-Identifier: GPL-3.0-only

#ifndef BALLTZE__RESOURCES_HPP
#define BALLTZE__RESOURCES_HPP

#define ID_LOADING_SCREEN_SHADER 101
#define ID_LOADING_SCREEN_BACKGROUND 102
#define ID_SPRITE_SHADER 103
#define ID_LUA_JSON_MODULE 104
#define ID_LUA_LUNA_MODULE 105
#define ID_LUA_INSPECT_MODULE 106

#endif
